implemented a rule to detect overwriting parent scope vars in for loo…
phpstan/phpstan-strict-rules pull request #99
Opened 2020-02-05 22:08 UTC by dktapps

…p init

closes #98

2020-08-28 13:20 UTC, dktapps commented
Updated, I hope this is suitable now 🙂

2020-08-30 13:16 UTC, ondrejmirtes requested changes
Otherwise ready to merge 👍

2020-08-30 13:16 UTC, ondrejmirtes commented on rules.neon
> +	- PHPStan\Rules\ForLoop\OverwriteVariablesWithForLoopInitRule
Adding rule to `rules` automatically applies the rule tag, this needs to be added as a tag-less service in the `services` section.

2020-08-30 15:42 UTC, merged

2020-08-30 15:42 UTC, ondrejmirtes commented
Thank you!

2020-08-30 15:43 UTC, ondrejmirtes commented
Tagged as 0.12.5.

2020-08-30 16:14 UTC, dktapps commented
Awesome, thanks!